name: js_wrapping_generator
version: 0.0.2-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: That package allows to generate wrappers for JS library in Dart.
homepage: https://github.com/a14n/dart-js-wrapping-generator
dependencies:
  analyzer_experimental: any
  js_wrapping: any
  meta: any
  path: any
dev_dependencies:
  unittest: any
