name: js_wrapping_generator
version: 0.0.2
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: That package allows to generate wrappers for JS library in Dart.
homepage: https://github.com/a14n/dart-js-wrapping-generator
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  analyzer: '>=0.10.1 <0.11.0'
  js_wrapping: '>=0.1.0 <0.2.0'
  path: '>=0.9.0 <0.10.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
